language: node_js

node_js:
  - "8"
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_95e24e700a4c_key -iv $encrypted_95e24e700a4c_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
# 改变文件权限
- chmod 600 ~/.ssh/id_rsa 
# 配置 ssh
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
# 配置 git 替换为自己的信息
- git config --global user.name 'Ghostdar'
- git config --global user.email 848760247@qq.com

# 安装依赖
install:
- npm install hexo-cli -g
- npm install

# 部署的命令
script:
- npm run deploy  # hexo clean && hexo g -d

# .travis.yml 配置
cache:
  directories:
    - node_modules
